### PR TITLE
feat: add support for React Router 6 stable

### PR DESCRIPTION
**Pull request by kyletsang**
There were some breaking changes from beta to stable, so this PR fixes that.  

Wasn't sure if we actually needed to render a `Route` inside the `LinkContainer`.  It was causing errors in v6 stable.  I think the hooks provided by React Router should be enough.  I tested using the visual tests page and everything looks like it works.

### CODE REVIEW

**Comment by Coolfeather2** [comment]
Still not working for me inside my project, or in the visual test page
Inside the visual test page, no links are there.

**Comment by kyletsang** [comment]
> 
> 
> Still not working for me inside my project, or in the visual test page Inside the visual test page, no links are there. (At least the nav page is not working)

You downloaded the branch this PR is referencing and npm installed?

**Review by mxschmitt — APPROVED** [review]
LGTM, but next time split applying formatting changes with changing logic. Thanks!

**Comment by Coolfeather2** [comment]
1. git cloned
2. checked out `react-router-v6-stable`
3. ran `npm install`
4. ran `npm run build`
5. ran `npm run visual-test`
image

```
node -v
v14.15.4
npm -v
6.14.10
```

**Comment by Coolfeather2** [comment]
Additionally, when packaging this up, or using npm link it doesn't work

package.json is looking for `./lib/index.js`, but `./lib/ReactRouterBootstrap.js` is being built

**Comment by kyletsang** [comment]
Yeah the NavItem thing should be fine.  There's supposed to be a NavLink underneath that gives it a little bit more styling

I'm going to merge this for now and address the build in another follow-up PR.

**Pull request merged**
