### PR TITLE
Remove unnecessary joinClasses dependency

### PR DESCRIPTION
**Pull request by heydiplo**
...which also ruins builds with React from CDN.

### CODE REVIEW

**Comment by taion** [comment]
This is fine in principle, except `lib/` contains the transpiled sources. You'll want to edit the file in `src/`.

**Comment by heydiplo** [comment]
:grin: sorry, fixed.

**Comment by taion** [comment]
Sorry, one last thing - don't update the files in `lib/`. We'll handle it when we release.

@mtscout6 What do you think of `.gitignore`ing the `lib/` path and putting `npm run build` in the `prepublish` script?

LGTM otherwise, need another @react-bootstrap/collaborators reviewer though.

**Comment by mathieumg** [comment]
> What do you think of .gitignoreing the lib/ path and putting npm run build in the prepublish script?

+1 :+1:  It's making this one-live review a pain, for instance. LGTM.

**Comment by aabenoja** [comment]
> What do you think of .gitignoreing the lib/ path and putting npm run build in the prepublish script?

:+1:

I would prefer to have the `lib` changes stripped before we pull this in, but that's just me.

**Comment by taion** [comment]
@aabenoja I agree, I'll make a PR once we merge this.

**Comment by mathieumg** [comment]
> I agree, I'll make a PR once we merge this.

Isn't that contradictory? :stuck_out_tongue:

**Comment by heydiplo** [comment]
Removed '`lib` changes, guys, it's pretty clean now.

**Comment by mtscout6** [comment]
@taion Once we setup a separate repo for the bower release and put scripts in place to automate that then I'd be fine with removing the lib folder from the repo. The only reason it's committed now is for the bower release.

**Comment by mtscout6** [comment]
See issue #48

**Comment by taion** [comment]
Brain fart, forgot that Bower doesn't work like NPM and actually looks at the repo.

**Pull request merged**
