### PR TITLE
Update MenuItemLink for react-bootstrap/react-bootstrap#686

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by dozoisch** [comment]
we need to bump the minor after this gets in since the requirement for peer RB has gone up from 0.15 to 0.22

**Comment by taion** [comment]
Yes, and I also want to add `classnames` as a dependency for Bower, which I'll do after we merge this PR.

**Comment by dozoisch** [comment]
Looks good!

**Comment by taion** [comment]
Actually, never mind on adding `classnames` as a dependency. It's already a subdependency of react-bootstrap anyway, and it's not worth the extra hassle of having another dep to keep up-to-date when we might move to only having the bundles anyway, which bundle in `classnames`.

**Pull request merged**
