### PR TITLE
Update dev-dependencies.

### PR DESCRIPTION
**Pull request by AlexKVal**
eslint
karma-cli

### CODE REVIEW

**Comment by AlexKVal** [comment]
Should we release next version ?
There are some commits after Jun 13, 2015.

**Comment by mtscout6** [comment]
LGTM

And yes a release sounds fine to me.

**Comment by AlexKVal** [comment]
@taion would you release next version ? :smiley:

**Comment by taion** [comment]
Been travelling and have had somewhat limited time to keep up. I can release if needed though - which branch and what version?

**Comment by AlexKVal** [comment]
Emm.. there is only one branch at this project `react-router-bootstrap`, so then it will be just next version. Isn't it ?

**Comment by taion** [comment]
Apologies - I thought this was the other repo. Do you want v0.16.1 or v0.17.0?

**Comment by AlexKVal** [comment]
I'm looking through the last commits history and there are basically dev-dependencies updates
that don't affect the code generated.

And there is only this `Remove 'classnames' dependency as a result of refactoring` https://github.com/react-bootstrap/react-router-bootstrap/pull/76 changing the code patch.
In spite of that `classnames` is not a dependency now, it wasn't in use anyway till that change.

But.. I don't know how other developers were using or not that `not public API` removed code.
I propose: Let's do it safely: `v0.17.0`

**Comment by taion** [comment]
We have v0.17.1 now (I messed up the Bower release for v0.17.0).

**Pull request merged**
