### PR TITLE
[changed] Replace everything with LinkContainer

### PR DESCRIPTION
**Pull request by taion**
It's painful and annoying to have to make a custom `Link` component for every component we want to use.

This replaces everything with a `LinkContainer` component that can wrap any React-Bootstrap component (and potentially plenty of others as well).

This is also targeted against React Router v1.0.0-rc1.

As part of this, I've stripped out a number of the visual tests that were trivial/pointless (pagination and thumbnails) or wrong (the dropdown, where normal menu items ignore the injected `onClick` prop).

### CODE REVIEW

**Comment by taion** [comment]
My intent would be to release this as v0.19.0. This will allow us to close almost all the current open issues.

**Comment by AlexKVal** [comment]
Very nice :+1: 
You've gutted it, indeed :smile:

**Comment by jquense** [comment]
I love this. one thought. maybe we add a trigger prop that defaults to onClick? then the user can wrap stuff that triggers other events? *cough* menuitem

**Comment by taion** [comment]
You mean for e.g. `onSelect`? I looked at that a little bit but the signature doesn't quite match, since this would ignore the `eventKey`.

Do you think it makes more sense to do that than to just have `MenuItem` call its `props.onClick`?

**Comment by mtscout6** [comment]
This looks really great! Should we consider renaming the project now that it's not specific to react-bootstrap?

**Comment by taion** [comment]
That's where I started - it's a little bit specific to React-Bootstrap, though. The `active` and `disabled` props really match the signature of our specific components. They're somewhat generic, but not 100%.

**Comment by mtscout6** [comment]
Gotcha!

**Comment by jquense** [comment]
> Do you think it makes more sense to do that than to just have MenuItem call its props.onClick?

I do, I was just thinking a little of both. More important to just fix the MenuItem tho. To the signature thing onSelect should provide the event first, so the preventDefault would work in that specific case. I know b/c thats what we are doing as of like 3 days ago :P

**Comment by taion** [comment]
I'm a little hesitant to do that, though, because the `handleClick` method from `Link` specifically calls into `props.onClick`, and I'd rather not copy-paste that entire method: https://github.com/rackt/react-router/blob/d88a051516d53eeb5c3fceb8f7ad0df325b3f404/modules/Link.js#L67-L68

I think I'd rather we just fix `MenuItem`.

Are we okay with releasing this?

**Comment by jquense** [comment]
LGTM

for reference tho I meant something more like:

```
  handleEvent(event = {}) {
    var allowTransition = true

    if (event.type === 'click' && isModifiedEvent(event) || !isLeftClickEvent(event))
      return

    if (event.defaultPrevented === true)
      allowTransition = false

    event.preventDefault()

    if (allowTransition)
      this.context.history.pushState(this.props.state, this.props.to, this.props.query)
  },

  render() {
    var { history } = this.context
    var { children, activeClassName, trigger, activeStyle, onlyActiveOnIndex, to, query, state, ...props } = this.props

    ;[].concat(trigger).forEach(eventName => {
      props[eventName] = chain(props[eventName], this.handleEvent)
    })
```

**Comment by taion** [comment]
Makes sense - could come in handy in case those use cases come up.

**Pull request merged**
