### PR TITLE
[added] Thumbnail links support

### PR DESCRIPTION
**Pull request by mdziekon**
This PR implements links support for ``<Thumbnail>`` component as ``<ThumbnailLink>``.

This is how visual test looks like:
react-router-bootstrap-thumbnail-visual

(**note**: as you can see, I've used Holder.js generated placeholder for the thumbnail, but I'm not sure whether "/assets" dir is a good place for it or not. If anyone have a better idea, please let me know.)

### CODE REVIEW

**Comment by AlexKVal** [comment]
`assets` folder is OK (`R-B` does the same)

LGTM :sparkle: 

Though I'm not sure about:
This PR changes the minimum version of `R-B` dependency:
from `0.15` to
```js
"react-bootstrap": ">=0.22.4"
```
[here](https://github.com/react-bootstrap/react-router-bootstrap/pull/102/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R67)

Anyway it needs one more approval of @react-bootstrap/collaborators 

--
If this PR merged as is, then the next version of `R-R-B` will be `0.19` because of this `"react-bootstrap": ">=0.22.4"` change, I presume.

**Comment by mdziekon** [comment]
According to ``R-B``'s Changelog, Thumbnail component was introduced in version 0.22.4 (https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md#v0224---mon-18-may-2015-165306-gmt)

I guessed dep version had to be changed to make sure we have this component in library.

**Comment by AlexKVal** [comment]
Ah.. Did think about it, sorry  :blush:

**Comment by dozoisch** [comment]
LGTM

**Comment by mtscout6** [comment]
LGTM

**Comment by taion** [comment]
I wonder if we can use some wrapper component for these generic linked components - i.e. just pass down `getLinkProps` to the wrapped component.

**Pull request merged**
