### PR TITLE
Allow For Testing Of LinkContainer When Not Wrapped In Router

### PR DESCRIPTION
**Pull request by cwbuecheler**
This is a slight change that allows for render testing on LinkContainers without requiring them to be wrapped by a router element.

For background information, please see issue #130 

NOTE: Unfortunately, two instances of the new test fail because an anchor is never being rendered at all, and I'm not sure why that's the case. I'm hoping it's something simple I'm overlooking and you might be able to quickly adjust it.

cc: @thom-nic

### CODE REVIEW

**Comment by cwbuecheler** [comment]
Apologies if I screwed up the pull request or didn't send it to the right branch -- new to this aspect of git/github.

**Comment by taion** [comment]
I would just drop the new test case - I don't think this needs to explicitly be covered.

And squash the commits down into something like `[fixed] Support LinkContainer without history`.

**Comment by cwbuecheler** [comment]
Will do, thanks.

**Comment by cwbuecheler** [comment]
Should be all set.

**Comment by taion** [comment]
Looks good. Can you squash the commits?

**Comment by cwbuecheler** [comment]
I thought I had, here: https://github.com/cwbuecheler/react-router-bootstrap/commit/104dad8bc95971eacbc8077cf7f5680cf2413e86  ... I'll try again.

**Comment by taion** [comment]
It's still showing up as 7 commits on this PR.

**Comment by cwbuecheler** [comment]
This isn't properly squashing, I think because I already pushed the commits to my branch. What I'm going to do is re-create the pull request with a single commit. Sorry for the confusion.

**Comment by taion** [comment]
Don't worry - I'll merge manually.

**Comment by cwbuecheler** [comment]
Thanks. I appreciate it. Clearly I have more to learn about git forking/branching/pull requests.

**Comment by taion** [comment]
https://github.com/react-bootstrap/react-router-bootstrap/commit/d1306b1cb6dd60a2299747e9ae9f405a031270ac

**Pull request closed without merging**
