### PR TITLE
Add support for "to" prop as a function

### PR DESCRIPTION
**Pull request by smashercosmo**

### CODE REVIEW

**Comment by taion** [comment]
RRv4 doesn't natively support this syntax though?

**Comment by smashercosmo** [comment]
No, it doesn't. In RR4 it can be achieved by wrapping Link component in Route component.

**Comment by taion** [comment]
Does the same strategy work here?

**Comment by smashercosmo** [comment]
Sorry, didn't quite understand. This PR is only for rr-v3 branch. I can make a separate PR to add support for this notation in master.

**Comment by taion** [comment]
oops, misread

**Comment by smashercosmo** [comment]
Would you mind cutting v23.3?

**Comment by taion** [comment]
I can take a look tomorrow.

**Pull request merged**
