### PR TITLE
Add eslintrc and convert to es6

### LINKED ISSUE #69: Implement eslint linting
As a start point these are the lines from the old (long unused) code:
```js
jshint: {
  enforceall: true,
  // jsx splat will make this fail
  eqnull: true,
  camelcase: false,
  nocomma: false,
  browser: true,
  singleGroups: false,
  emitErrors: true,
  failOnHint: true
}
```

### PR DESCRIPTION
**Pull request by mtscout6**
Resolves #69

### CODE REVIEW

**Comment by mtscout6** [comment]
I know I didn't address all the eslint warnings, but it was enough for now, as it's at least the equivalent to what it was before ES6. I need to call it a night.

**Comment by AlexKVal** [comment]
> I know I didn't address all the eslint warnings

I think I could address them within the next few days.

**Comment by AlexKVal** [comment]
LGTM

**Comment by taion** [comment]
Wow, you guys are awesome. Thanks!

**Comment by mtscout6** [comment]
I didn't want to write the bower import transposer twice, so I just converted everything to ES6 :smile:

**Pull request merged**
