### PR TITLE
Remove extraneous dependencies.

### PR DESCRIPTION
**Pull request by AlexKVal**

### CODE REVIEW

**Comment by taion** [comment]
LGTM

**Comment by mtscout6** [comment]
Weren't those used for the visual test?

**Comment by AlexKVal** [comment]
Nope. There were in no use at all.

**Comment by taion** [comment]
Wait, it looks like they were: https://github.com/react-bootstrap/react-router-bootstrap/blob/v0.17.2/tests/visual.js - this is trying to import a LESS file.

**Comment by AlexKVal** [comment]
Yeah. But `npm run visual-test` is broken.
There are only folders with src files in browser.

**Comment by AlexKVal** [comment]
The same history as with `IE8` dev support was in `React-Bootstrap`.
There are only remnants. But they are broken.
And we have to decide remove them, or fix them.

**Comment by AlexKVal** [comment]
It looks like that: (before we removed those unused deps)
screen shot 2015-07-13 at 6 38 57 pm

then I open in browser http://localhost:8080/webpack-dev-server/
screen shot 2015-07-13 at 6 39 11 pm

then I go to `tests/visual`
screen shot 2015-07-13 at 6 39 37 pm

See ? Nothing. Broken.

**Comment by mtscout6** [comment]
I recently fixed those in #85 so they should be working.

**Comment by AlexKVal** [comment]
Alas, nope :)
I've made those screenshots with #85 fix.
screen shot 2015-07-14 at 1 29 25 am

**Comment by mtscout6** [comment]
Neither of those urls are the visual test. You should hit: http://localhost:8080/public/visual#/

**Comment by mtscout6** [comment]
For example the url: http://localhost:8080/public/visual#/button

Should look like:

screen shot 2015-07-13 at 5 42 41 pm

Instead with this change it's blank and you'll see the console output:

```
➜  react-router-bootstrap git:(master) npm run visual-test

> react-router-bootstrap@0.17.2 visual-test /Users/smithm/dev/react-router-bootstrap
> webpack-dev-server --config webpack.test.config.babel.js

http://localhost:8080/webpack-dev-server/
webpack result is served from /public/
content is served from /Users/smithm/dev/react-router-bootstrap
Hash: a270f3eafda70a61c66a
Version: webpack 1.10.1
Time: 1750ms
    Asset     Size  Chunks             Chunk Names
visual.js  2.13 MB       0  [emitted]  visual
chunk    {0} visual.js (visual) 781 kB [rendered]
    [0] multi visual 28 bytes {0} [built]
    [1] ./tests/visual.js 82 bytes {0} [built] [1 error]
    [3] ./tests/visual/app.js 1.52 kB {0} [built]
    [4] ./~/react/react.js 41 bytes {0} [built]
    [5] ./~/react/lib/React.js 4.79 kB {0} [built]
    [6] ./~/webpack-dev-server/~/node-libs-browser/~/process/browser.js 2.02 kB {0} [built]
    [7] ./~/react/lib/EventPluginUtils.js 6.75 kB {0} [built]
    [8] ./~/react/lib/EventConstants.js 1.56 kB {0} [built]
    [9] ./~/react/lib/keyMirror.js 1.3 kB {0} [built]
   [10] ./~/react/lib/invariant.js 1.54 kB {0} [built]
   [11] ./~/react/lib/ReactChildren.js 4.74 kB {0} [built]
   [12] ./~/react/lib/PooledClass.js 3.27 kB {0} [built]
   [13] ./~/react/lib/ReactFragment.js 5.74 kB {0} [built]
   [14] ./~/react/lib/ReactElement.js 8.27 kB {0} [built]
   [15] ./~/react/lib/ReactContext.js 1.97 kB {0} [built]
   [16] ./~/react/lib/Object.assign.js 1.26 kB {0} [built]
   [17] ./~/react/lib/emptyObject.js 483 bytes {0} [built]
   [18] ./~/react/lib/warning.js 1.9 kB {0} [built]
   [19] ./~/react/lib/emptyFunction.js 1.06 kB {0} [built]
   [20] ./~/react/lib/ReactCurrentOwner.js 738 bytes {0} [built]
   [21] ./~/react/lib/traverseAllChildren.js 7.54 kB {0} [built]
   [22] ./~/react/lib/getIteratorFn.js 1.18 kB {0} [built]
   [23] ./~/react/lib/ReactInstanceHandles.js 10.6 kB {0} [built]
   [24] ./~/react/lib/ReactRootIndex.js 723 bytes {0} [built]
   [25] ./~/react/lib/ReactComponent.js 5.04 kB {0} [built]
   [26] ./~/react/lib/ReactUpdateQueue.js 9.95 kB {0} [built]
   [27] ./~/react/lib/ReactUpdates.js 9.26 kB {0} [built]
   [28] ./~/react/lib/CallbackQueue.js 2.47 kB {0} [built]
   [29] ./~/react/lib/ReactPerf.js 2.55 kB {0} [built]
   [30] ./~/react/lib/ReactReconciler.js 3.6 kB {0} [built]
   [31] ./~/react/lib/ReactRef.js 2 kB {0} [built]
   [32] ./~/react/lib/ReactOwner.js 3.69 kB {0} [built]
   [33] ./~/react/lib/ReactElementValidator.js 14.2 kB {0} [built]
   [34] ./~/react/lib/ReactPropTypeLocations.js 543 bytes {0} [built]
   [35] ./~/react/lib/ReactPropTypeLocationNames.js 612 bytes {0} [built]
   [36] ./~/react/lib/ReactNativeComponent.js 3.22 kB {0} [built]
   [37] ./~/react/lib/Transaction.js 9.36 kB {0} [built]
   [38] ./~/react/lib/ReactLifeCycle.js 1.25 kB {0} [built]
   [39] ./~/react/lib/ReactInstanceMap.js 1.25 kB {0} [built]
   [40] ./~/react/lib/ReactClass.js 30 kB {0} [built]
   [41] ./~/react/lib/ReactErrorUtils.js 843 bytes {0} [built]
   [42] ./~/react/lib/keyOf.js 1.1 kB {0} [built]
   [43] ./~/react/lib/ReactDOM.js 3.29 kB {0} [built]
   [44] ./~/react/lib/mapObject.js 1.47 kB {0} [built]
   [45] ./~/react/lib/ReactDOMTextComponent.js 3.59 kB {0} [built]
   [46] ./~/react/lib/DOMPropertyOperations.js 6.03 kB {0} [built]
   [47] ./~/react/lib/DOMProperty.js 10.2 kB {0} [built]
   [48] ./~/react/lib/quoteAttributeValueForBrowser.js 747 bytes {0} [built]
   [49] ./~/react/lib/escapeTextContentForBrowser.js 850 bytes {0} [built]
   [50] ./~/react/lib/ReactComponentBrowserEnvironment.js 1.29 kB {0} [built]
   [51] ./~/react/lib/ReactDOMIDOperations.js 5.49 kB {0} [built]
   [52] ./~/react/lib/CSSPropertyOperations.js 5.31 kB {0} [built]
   [53] ./~/react/lib/CSSProperty.js 3.14 kB {0} [built]
   [54] ./~/react/lib/ExecutionEnvironment.js 1.13 kB {0} [built]
   [55] ./~/react/lib/camelizeStyleName.js 1.03 kB {0} [built]
   [56] ./~/react/lib/camelize.js 714 bytes {0} [built]
   [57] ./~/react/lib/dangerousStyleValue.js 1.93 kB {0} [built]
   [58] ./~/react/lib/hyphenateStyleName.js 1.01 kB {0} [built]
   [59] ./~/react/lib/hyphenate.js 808 bytes {0} [built]
   [60] ./~/react/lib/memoizeStringOnly.js 778 bytes {0} [built]
   [61] ./~/react/lib/DOMChildrenOperations.js 4.51 kB {0} [built]
   [62] ./~/react/lib/Danger.js 7.19 kB {0} [built]
   [63] ./~/react/lib/createNodesFromMarkup.js 2.69 kB {0} [built]
   [64] ./~/react/lib/createArrayFromMixed.js 2.37 kB {0} [built]
   [65] ./~/react/lib/toArray.js 2.08 kB {0} [built]
   [66] ./~/react/lib/getMarkupWrap.js 3.16 kB {0} [built]
   [67] ./~/react/lib/ReactMultiChildUpdateTypes.js 835 bytes {0} [built]
   [68] ./~/react/lib/setTextContent.js 1.19 kB {0} [built]
   [69] ./~/react/lib/setInnerHTML.js 3.03 kB {0} [built]
   [70] ./~/react/lib/ReactMount.js 31.2 kB {0} [built]
   [71] ./~/react/lib/ReactBrowserEventEmitter.js 12.3 kB {0} [built]
   [72] ./~/react/lib/EventPluginHub.js 8.23 kB {0} [built]
   [73] ./~/react/lib/EventPluginRegistry.js 8.92 kB {0} [built]
   [74] ./~/react/lib/accumulateInto.js 1.74 kB {0} [built]
   [75] ./~/react/lib/forEachAccumulated.js 889 bytes {0} [built]
   [76] ./~/react/lib/ReactEventEmitterMixin.js 1.32 kB {0} [built]
   [77] ./~/react/lib/ViewportMetrics.js 638 bytes {0} [built]
   [78] ./~/react/lib/isEventSupported.js 1.98 kB {0} [built]
   [79] ./~/react/lib/ReactEmptyComponent.js 2.83 kB {0} [built]
   [80] ./~/react/lib/ReactMarkupChecksum.js 1.32 kB {0} [built]
   [81] ./~/react/lib/adler32.js 885 bytes {0} [built]
   [82] ./~/react/lib/containsNode.js 1.23 kB {0} [built]
   [83] ./~/react/lib/isTextNode.js 614 bytes {0} [built]
   [84] ./~/react/lib/isNode.js 718 bytes {0} [built]
   [85] ./~/react/lib/getReactRootElementInContainer.js 888 bytes {0} [built]
   [86] ./~/react/lib/instantiateReactComponent.js 4.59 kB {0} [built]
   [87] ./~/react/lib/ReactCompositeComponent.js 29.4 kB {0} [built]
   [88] ./~/react/lib/ReactComponentEnvironment.js 1.7 kB {0} [built]
   [89] ./~/react/lib/shouldUpdateReactComponent.js 4.09 kB {0} [built]
   [90] ./~/react/lib/ReactDOMComponent.js 17 kB {0} [built]
   [91] ./~/react/lib/ReactMultiChild.js 12 kB {0} [built]
   [92] ./~/react/lib/ReactChildReconciler.js 4.17 kB {0} [built]
   [93] ./~/react/lib/flattenChildren.js 1.68 kB {0} [built]
   [94] ./~/react/lib/ReactDefaultInjection.js 5.44 kB {0} [built]
   [95] ./~/react/lib/BeforeInputEventPlugin.js 15.1 kB {0} [built]
   [96] ./~/react/lib/EventPropagators.js 4.65 kB {0} [built]
   [97] ./~/react/lib/FallbackCompositionState.js 2.38 kB {0} [built]
   [98] ./~/react/lib/getTextContentAccessor.js 1 kB {0} [built]
   [99] ./~/react/lib/SyntheticCompositionEvent.js 1.14 kB {0} [built]
  [100] ./~/react/lib/SyntheticEvent.js 4.85 kB {0} [built]
  [101] ./~/react/lib/getEventTarget.js 931 bytes {0} [built]
  [102] ./~/react/lib/SyntheticInputEvent.js 1.12 kB {0} [built]
  [103] ./~/react/lib/ChangeEventPlugin.js 11.5 kB {0} [built]
  [104] ./~/react/lib/isTextInputElement.js 975 bytes {0} [built]
  [105] ./~/react/lib/ClientReactRootIndex.js 551 bytes {0} [built]
  [106] ./~/react/lib/DefaultEventPluginOrder.js 1.34 kB {0} [built]
  [107] ./~/react/lib/EnterLeaveEventPlugin.js 3.86 kB {0} [built]
  [108] ./~/react/lib/SyntheticMouseEvent.js 2.2 kB {0} [built]
  [109] ./~/react/lib/SyntheticUIEvent.js 1.6 kB {0} [built]
  [110] ./~/react/lib/getEventModifierState.js 1.33 kB {0} [built]
  [111] ./~/react/lib/HTMLDOMPropertyConfig.js 6.53 kB {0} [built]
  [112] ./~/react/lib/MobileSafariClickEventPlugin.js 1.72 kB {0} [built]
  [113] ./~/react/lib/ReactBrowserComponentMixin.js 715 bytes {0} [built]
  [114] ./~/react/lib/findDOMNode.js 2.4 kB {0} [built]
  [115] ./~/react/lib/ReactDefaultBatchingStrategy.js 1.91 kB {0} [built]
  [116] ./~/react/lib/ReactDOMButton.js 1.61 kB {0} [built]
  [117] ./~/react/lib/AutoFocusMixin.js 595 bytes {0} [built]
  [118] ./~/react/lib/focusNode.js 728 bytes {0} [built]
  [119] ./~/react/lib/ReactDOMForm.js 1.64 kB {0} [built]
  [120] ./~/react/lib/LocalEventTrapMixin.js 1.74 kB {0} [built]
  [121] ./~/react/lib/ReactDOMImg.js 1.41 kB {0} [built]
  [122] ./~/react/lib/ReactDOMIframe.js 1.37 kB {0} [built]
  [123] ./~/react/lib/ReactDOMInput.js 5.91 kB {0} [built]
  [124] ./~/react/lib/LinkedValueUtils.js 4.75 kB {0} [built]
  [125] ./~/react/lib/ReactPropTypes.js 11.1 kB {0} [built]
  [126] ./~/react/lib/ReactDOMOption.js 1.34 kB {0} [built]
  [127] ./~/react/lib/ReactDOMSelect.js 5.21 kB {0} [built]
  [128] ./~/react/lib/ReactDOMTextarea.js 4.71 kB {0} [built]
  [129] ./~/react/lib/ReactEventListener.js 5.51 kB {0} [built]
  [130] ./~/react/lib/EventListener.js 2.67 kB {0} [built]
  [131] ./~/react/lib/getUnboundedScrollPosition.js 1.09 kB {0} [built]
  [132] ./~/react/lib/ReactInjection.js 1.47 kB {0} [built]
  [133] ./~/react/lib/ReactReconcileTransaction.js 4.92 kB {0} [built]
  [134] ./~/react/lib/ReactInputSelection.js 4.25 kB {0} [built]
  [135] ./~/react/lib/ReactDOMSelection.js 6.14 kB {0} [built]
  [136] ./~/react/lib/getNodeForCharacterOffset.js 1.66 kB {0} [built]
  [137] ./~/react/lib/getActiveElement.js 788 bytes {0} [built]
  [138] ./~/react/lib/ReactPutListenerQueue.js 1.33 kB {0} [built]
  [139] ./~/react/lib/SelectEventPlugin.js 5.84 kB {0} [built]
  [140] ./~/react/lib/shallowEqual.js 1.1 kB {0} [built]
  [141] ./~/react/lib/ServerReactRootIndex.js 868 bytes {0} [built]
  [142] ./~/react/lib/SimpleEventPlugin.js 12.5 kB {0} [built]
  [143] ./~/react/lib/SyntheticDragEvent.js 1.09 kB {0} [built]
  [144] ./~/react/lib/SyntheticClipboardEvent.js 1.22 kB {0} [built]
  [145] ./~/react/lib/SyntheticFocusEvent.js 1.08 kB {0} [built]
  [146] ./~/react/lib/SyntheticKeyboardEvent.js 2.72 kB {0} [built]
  [147] ./~/react/lib/getEventCharCode.js 1.56 kB {0} [built]
  [148] ./~/react/lib/getEventKey.js 2.93 kB {0} [built]
  [149] ./~/react/lib/SyntheticTouchEvent.js 1.3 kB {0} [built]
  [150] ./~/react/lib/SyntheticWheelEvent.js 1.99 kB {0} [built]
  [151] ./~/react/lib/SVGDOMPropertyConfig.js 2.8 kB {0} [built]
  [152] ./~/react/lib/createFullPageComponent.js 1.9 kB {0} [built]
  [153] ./~/react/lib/ReactDefaultPerf.js 8.55 kB {0} [built]
  [154] ./~/react/lib/ReactDefaultPerfAnalysis.js 5.67 kB {0} [built]
  [155] ./~/react/lib/performanceNow.js 767 bytes {0} [built]
  [156] ./~/react/lib/performance.js 625 bytes {0} [built]
  [157] ./~/react/lib/ReactServerRendering.js 2.58 kB {0} [built]
  [158] ./~/react/lib/ReactServerRenderingTransaction.js 2.72 kB {0} [built]
  [159] ./~/react/lib/onlyChild.js 1.23 kB {0} [built]
  [160] ./~/react-router/lib/index.js 1.41 kB {0} [built]
  [161] ./~/react-router/lib/components/DefaultRoute.js 1.59 kB {0} [built]
  [162] ./~/react-router/lib/PropTypes.js 730 bytes {0} [built]
  [163] ./~/react-router/lib/Route.js 8.31 kB {0} [built]
  [164] ./~/react-router/lib/PathUtils.js 4.23 kB {0} [built]
  [165] ./~/react-router/~/object-assign/index.js 484 bytes {0} [built]
  [166] ./~/react-router/~/qs/index.js 36 bytes {0} [built]
  [167] ./~/react-router/~/qs/lib/index.js 200 bytes {0} [built]
  [168] ./~/react-router/~/qs/lib/stringify.js 2.32 kB {0} [built]
  [169] ./~/react-router/~/qs/lib/utils.js 2.4 kB {0} [built]
  [170] ./~/react-router/~/qs/lib/parse.js 4.04 kB {0} [built]
  [171] ./~/react-router/lib/components/RouteHandler.js 3.9 kB {0} [built]
  [172] ./~/react-router/lib/components/ContextWrapper.js 1.88 kB {0} [built]
  [173] ./~/react-router/lib/components/Route.js 3.56 kB {0} [built]
  [174] ./~/react-router/lib/components/Link.js 4.71 kB {0} [built]
  [175] ./~/react-router/lib/components/NotFoundRoute.js 1.64 kB {0} [built]
  [176] ./~/react-router/lib/components/Redirect.js 1.44 kB {0} [built]
  [177] ./~/react-router/lib/locations/HashLocation.js 2.67 kB {0} [built]
  [178] ./~/react-router/lib/actions/LocationActions.js 410 bytes {0} [built]
  [179] ./~/react-router/lib/History.js 616 bytes {0} [built]
  [180] ./~/react-router/lib/locations/HistoryLocation.js 1.91 kB {0} [built]
  [181] ./~/react-router/lib/locations/RefreshLocation.js 615 bytes {0} [built]
  [182] ./~/react-router/lib/locations/StaticLocation.js 1.85 kB {0} [built]
  [183] ./~/react-router/lib/locations/TestLocation.js 2.93 kB {0} [built]
  [184] ./~/react-router/lib/behaviors/ImitateBrowserBehavior.js 663 bytes {0} [built]
  [185] ./~/react-router/lib/behaviors/ScrollToTopBehavior.js 270 bytes {0} [built]
  [186] ./~/react-router/lib/Navigation.js 1.67 kB {0} [built]
  [187] ./~/react-router/lib/State.js 1.65 kB {0} [built]
  [188] ./~/react-router/lib/createRoutesFromReactChildren.js 2.52 kB {0} [built]
  [189] ./~/react-router/lib/createRouter.js 17.3 kB {0} [built]
  [190] ./~/react-router/lib/ScrollHistory.js 2.15 kB {0} [built]
  [191] ./~/react-router/lib/getWindowScrollPosition.js 511 bytes {0} [built]
  [192] ./~/react-router/lib/isReactChildren.js 295 bytes {0} [built]
  [193] ./~/react-router/lib/Transition.js 2.02 kB {0} [built]
  [194] ./~/react-router/lib/Cancellation.js 190 bytes {0} [built]
  [195] ./~/react-router/lib/Redirect.js 200 bytes {0} [built]
  [196] ./~/react-router/lib/Match.js 2.95 kB {0} [built]
  [197] ./~/react-router/lib/supportsHistory.js 665 bytes {0} [built]
  [198] ./~/react-router/lib/runRouter.js 1.21 kB {0} [built]
  [199] ./tests/visual/home.js 1.65 kB {0} [built]
  [200] ./tests/visual/ButtonVisual.js 3.51 kB {0} [built]
  [201] ./~/react-bootstrap/lib/ButtonToolbar.js 1.35 kB {0} [built]
  [202] ./~/react-bootstrap/~/classnames/index.js 1.02 kB {0} [built]
  [203] ./~/react-bootstrap/lib/BootstrapMixin.js 1.8 kB {0} [built]
  [204] ./~/react-bootstrap/lib/styleMaps.js 4.42 kB {0} [built]
  [205] ./~/react-bootstrap/lib/utils/CustomPropTypes.js 5.65 kB {0} [built]
  [206] ./~/react-bootstrap/lib/Button.js 3.18 kB {0} [built]
  [207] ./src/ButtonLink.js 1.18 kB {0} [built]
  [208] ./src/LinkMixin.js 2.63 kB {0} [built]
  [209] ./tests/visual/NavItemVisual.js 2.83 kB {0} [built]
  [210] ./~/react-bootstrap/lib/Nav.js 4.71 kB {0} [built]
  [211] ./~/react-bootstrap/lib/CollapsibleMixin.js 5.06 kB {0} [built]
  [212] ./~/react-bootstrap/lib/utils/TransitionEvents.js 3.43 kB {0} [built]
  [213] ./~/react-bootstrap/lib/utils/domUtils.js 4.95 kB {0} [built]
  [214] ./~/react-bootstrap/lib/utils/ValidComponentChildren.js 2.79 kB {0} [built]
  [215] ./~/react-bootstrap/lib/utils/createChainedFunction.js 1.08 kB {0} [built]
  [216] ./~/react-bootstrap/lib/NavItem.js 3.22 kB {0} [built]
  [217] ./src/NavItemLink.js 1.19 kB {0} [built]
  [218] ./tests/visual/MenuItemVisual.js 3.78 kB {0} [built]
  [219] ./~/react-bootstrap/lib/SplitButton.js 4.37 kB {0} [built]
  [220] ./~/react-bootstrap/lib/DropdownStateMixin.js 2.51 kB {0} [built]
  [221] ./~/react-bootstrap/lib/utils/EventListener.js 1.91 kB {0} [built]
  [222] ./~/react-bootstrap/lib/ButtonGroup.js 2.2 kB {0} [built]
  [223] ./~/react-bootstrap/lib/DropdownMenu.js 2.01 kB {0} [built]
  [224] ./~/react-bootstrap/lib/MenuItem.js 2.5 kB {0} [built]
  [225] ./src/MenuItemLink.js 1.29 kB {0} [built]
  [226] ./tests/visual/ListGroupItemVisual.js 4.63 kB {0} [built]
  [227] ./~/react-bootstrap/lib/ListGroup.js 4.38 kB {0} [built]
  [228] ./~/react-bootstrap/lib/ListGroupItem.js 3.63 kB {0} [built]
  [229] ./src/ListGroupItemLink.js 1.24 kB {0} [built]

ERROR in ./~/bootstrap/less/bootstrap.less
Module parse failed: /Users/smithm/dev/react-router-bootstrap/node_modules/bootstrap/less/bootstrap.less Line 8: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
|
| // Core variables and mixins
| @import "variables.less";
| @import "mixins.less";
|
 @ ./tests/visual.js 3:0-40
webpack: bundle is now VALID.
```

**Comment by AlexKVal** [comment]
You want me to run me down by this loooong console output :smile: I got it. 
Sorry that I've introduced this mess. :cake: 
But to my excuse there is no any clue what link I should open for visual tests :stuck_out_tongue_closed_eyes: 

Tomorrow I'll fix this all :boat:

**Comment by mtscout6** [comment]
That's partly my fault for not putting that link somewhere. I thought at some point along the line it was addressed, but I guess not. My apologies.

**Pull request merged**
