### PR TITLE
Switch to 'babel'

### PR DESCRIPTION
**Pull request by AlexKVal**
Webpack configs have been rewritten to simplify `npm scripts`
`webpack lib/index.js lib/ReactRouterBootstrap.js && COMPRESS=1 webpack lib/index.js lib/ReactRouterBootstrap.min.js",`

Addressed `npm` warnings
`The peer dependency node-libs-browser@>= 0.4.0 <=0.6.0 included from webpack`
`The peer dependency babel-core@* included from babel-loader`

`jshint` checking has been removed because it did not work anyway
because it was checking `jsx` and there are no any `jsx` files.
`{ test: /\.jsx?$/, loader: "jshint", exclude: path.join(__dirname, 'node_modules') },`

Sourcemaps has been added for `min` version
`devtool: process.env.COMPRESS && 'source-map'`

I'll create issues about linting
and for `npm run visual-test`

Closes https://github.com/react-bootstrap/react-router-bootstrap/issues/64

### CODE REVIEW

**Comment by mtscout6** [comment]
LGTM

**Comment by mtscout6** [comment]
@taion will be pleased!

**Comment by dozoisch** [comment]
great!

**Comment by taion** [comment]
Wow! That's great. Thanks. LGTM as well.

**Comment by AlexKVal** [comment]
:cherries: :smile:

**Pull request merged**
