### PR TITLE
Add NavDropdown + LinkContainer and MenuItem to visual-test

### PR DESCRIPTION
**Pull request by TimDaub**
Based on comment in #126

### CODE REVIEW

**Comment by taion** [comment]
Sure. So

1. We should add the `NavDropdown` to both examples.
2. I don't think `LinkContainer` actually works with dropdowns right now

**Comment by taion** [comment]
Should work after https://github.com/react-bootstrap/react-router-bootstrap/issues/112 and we can bring back the dropdown visual test.

But anyway if you want this merged, please do add the dropdown to the baseline example.

**Comment by TimDaub** [comment]
Ok,

will do it on monday.

**Comment by taion** [comment]
Might be superseded by #129 which adds back the old `MenuItem` thing.

**Comment by AlexKVal** [comment]
I've rebased it on master with #128 and #129 merged and `npm run visual-test`
It looks as:
screen shot 2015-10-19 at 1 36 56 pm

Everything else seems OK too.

**Comment by taion** [comment]
>We should add the `NavDropdown` to both examples.

The point of this is that they match. Probably also add a title to the dropdown.

**Comment by taion** [comment]
Closing for staleness.

**Pull request closed without merging**
